---
- name: Install default Apache Web Server
  hosts: all
  become: yes

  vars:
    source_dir: ./html
    destin_dir: /var/www

  tasks:
  - block: # ===For REDHAT===
    - name: Update system in RedHat
      yum:
       name: "*"
       state: latest

    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest

    - name: Copy App to Servers
      synchronize: src={{ source_dir }} dest={{ destin_dir }}
      notify: Restart Apache in RedHat
  
    - name: Start Apache and Enable it on the every boot
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block: # ===For DEBIAN===
    - name: Update system in Debian
      apt:
       update_cache: true
       cache_valid_time: 3600
       force_apt_get: true

    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest

    - name: Copy App to Servers
      synchronize: src={{ source_dir }} dest={{ destin_dir }}
      notify: Restart Apache in Debian
  
    - name: Start Apache and Enable it on the every boot
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache in RedHat
    service: name=httpd state=restarted

  - name: Restart Apache in Debian
    service: name=apache2 state=restarted
